"""empty message

Revision ID: 026ef85767a8
Revises: 0730dca97624
Create Date: 2026-03-25 16:55:10.375918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026ef85767a8'
down_revision: Union[str, Sequence[str], None] = '0730dca97624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ###
