"""empty message

Revision ID: 0b0924ab237e
Revises: 972c39853f86
Create Date: 2025-12-08 16:14:32.931955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0924ab237e'
down_revision: Union[str, Sequence[str], None] = '972c39853f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('work_types', 'equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('work_types', 'category')
    # ### end Alembic commands ###
