"""empty message

Revision ID: 1627d125452f
Revises: 4b0133736ff8
Create Date: 2025-10-12 19:04:08.172595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1627d125452f'
down_revision: Union[str, Sequence[str], None] = '4b0133736ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('category', sa.String(), nullable=False))
    op.drop_constraint(op.f('equipment_name_key'), 'equipment', type_='unique')
    op.drop_column('work_types', 'requires_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('requires_photo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('equipment_name_key'), 'equipment', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('equipment', 'category')
    # ### end Alembic commands ###
