"""empty message

Revision ID: 2273555f11be
Revises: 52d84eed6d3d
Create Date: 2025-12-04 20:24:20.491198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2273555f11be'
down_revision: Union[str, Sequence[str], None] = '52d84eed6d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_persons', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_persons', 'position')
    # ### end Alembic commands ###
