"""empty message

Revision ID: 28dcc5470257
Revises: 9ba78ba595a3
Create Date: 2025-11-02 16:39:44.799043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28dcc5470257'
down_revision: Union[str, Sequence[str], None] = '9ba78ba595a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_persons', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('task_history', sa.Column('contact_person_phone', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('contact_person_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'contact_person_phone')
    op.drop_column('task_history', 'contact_person_phone')
    op.drop_column('contact_persons', 'phone')
    # ### end Alembic commands ###
