"""empty message

Revision ID: 2c40f1e4c4e2
Revises: 91b5c9c416bb
Create Date: 2025-10-26 16:02:51.622571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c40f1e4c4e2'
down_revision: Union[str, Sequence[str], None] = '91b5c9c416bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_history_company_id'), 'task_history', ['company_id'], unique=False)
    op.create_foreign_key(None, 'task_history', 'client_companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'client_companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_column('tasks', 'company_id')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_index(op.f('ix_task_history_company_id'), table_name='task_history')
    op.drop_column('task_history', 'company_id')
    # ### end Alembic commands ###
