"""empty message

Revision ID: 462a5080cea0
Revises: 2c40f1e4c4e2
Create Date: 2025-10-29 21:39:23.349795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462a5080cea0'
down_revision: Union[str, Sequence[str], None] = '2c40f1e4c4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=False)
    # ### end Alembic commands ###
