"""empty message

Revision ID: 4756b4fc78e3
Revises: 6688d1827d9a
Create Date: 2025-10-03 13:54:30.648025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4756b4fc78e3'
down_revision: Union[str, Sequence[str], None] = '6688d1827d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'client',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'vehicle_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'assignment_type',
               existing_type=postgresql.ENUM('individual', 'broadcast', name='assignmenttype'),
               nullable=True)
    op.alter_column('tasks', 'logist_contact_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tasks', 'client_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('tasks', 'montajnik_reward',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_tasks_assignment_type'), 'tasks', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_is_draft'), 'tasks', ['is_draft'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_is_draft'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignment_type'), table_name='tasks')
    op.alter_column('tasks', 'montajnik_reward',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('tasks', 'client_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('tasks', 'logist_contact_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('tasks', 'assignment_type',
               existing_type=postgresql.ENUM('individual', 'broadcast', name='assignmenttype'),
               nullable=False)
    op.alter_column('tasks', 'vehicle_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'client',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('tasks', 'version')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###
