"""empty message

Revision ID: 4a60005c777a
Revises: 95b6b6ca6ea2
Create Date: 2025-10-16 20:08:08.426362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a60005c777a'
down_revision: Union[str, Sequence[str], None] = '95b6b6ca6ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'work_types_ids')
    op.drop_column('task_history', 'equipment_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('equipment_ids', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('task_history', sa.Column('work_types_ids', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
