"""empty message

Revision ID: 4b0133736ff8
Revises: a9cd18d687bb
Create Date: 2025-10-09 14:39:01.372471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0133736ff8'
down_revision: Union[str, Sequence[str], None] = 'a9cd18d687bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('linked_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_mappings_telegram_id'), 'telegram_mappings', ['telegram_id'], unique=True)
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_column('users', 'chat_id')
    op.drop_index(op.f('ix_telegram_mappings_telegram_id'), table_name='telegram_mappings')
    op.drop_table('telegram_mappings')
    # ### end Alembic commands ###
