"""empty message

Revision ID: 4c3e926e97fa
Revises: a7e237bf0355
Create Date: 2025-10-22 14:09:22.114722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3e926e97fa'
down_revision: Union[str, Sequence[str], None] = 'a7e237bf0355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('equipment_snapshot', sa.JSON(), nullable=True))
    op.add_column('task_history', sa.Column('work_types_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'work_types_snapshot')
    op.drop_column('task_history', 'equipment_snapshot')
    # ### end Alembic commands ###
