"""empty message

Revision ID: 52894ad1993d
Revises: 7643438e6fc9
Create Date: 2026-02-02 18:36:58.757543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52894ad1993d'
down_revision: Union[str, Sequence[str], None] = '7643438e6fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_user_company_id'), 'districts', ['user_company_id'], unique=False)
    op.add_column('tasks', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_district_id'), 'tasks', ['district_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_foreign_key(None, 'users', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_column('users', 'district_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_district_id'), table_name='tasks')
    op.drop_column('tasks', 'district_id')
    op.drop_index(op.f('ix_districts_user_company_id'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
