"""empty message

Revision ID: 52d84eed6d3d
Revises: f647add9747e
Create Date: 2025-12-02 17:54:13.561169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52d84eed6d3d'
down_revision: Union[str, Sequence[str], None] = 'f647add9747e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_reports', sa.Column('reviewed_at_logist', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_reports', sa.Column('reviewed_at_tech_supp', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('task_reports', 'reviewed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_reports', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('task_reports', 'reviewed_at_tech_supp')
    op.drop_column('task_reports', 'reviewed_at_logist')
    # ### end Alembic commands ###
