"""empty message

Revision ID: 5932468b4e6e
Revises: 90ec311184e8
Create Date: 2025-10-16 02:00:04.217329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5932468b4e6e'
down_revision: Union[str, Sequence[str], None] = '90ec311184e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('client', sa.String(), nullable=True))
    op.add_column('task_history', sa.Column('vehicle_info', sa.String(), nullable=True))
    op.add_column('task_history', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_history', sa.Column('location', sa.String(), nullable=True))
    op.add_column('task_history', sa.Column('comment_field', sa.Text(), nullable=True))
    op.add_column('task_history', sa.Column('status', sa.Enum('new', 'accepted', 'started', 'completed', 'inspection', 'returned', name='taskstatus'), nullable=True))
    op.add_column('task_history', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('task_history', sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('task_history', sa.Column('montajnik_reward', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('task_history', sa.Column('photo_required', sa.Boolean(), nullable=True))
    op.add_column('task_history', sa.Column('assignment_type', sa.Enum('individual', 'broadcast', name='assignmenttype'), nullable=True))
    op.create_index(op.f('ix_task_history_assigned_user_id'), 'task_history', ['assigned_user_id'], unique=False)
    op.create_foreign_key(None, 'task_history', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_index(op.f('ix_task_history_assigned_user_id'), table_name='task_history')
    op.drop_column('task_history', 'assignment_type')
    op.drop_column('task_history', 'photo_required')
    op.drop_column('task_history', 'montajnik_reward')
    op.drop_column('task_history', 'client_price')
    op.drop_column('task_history', 'assigned_user_id')
    op.drop_column('task_history', 'status')
    op.drop_column('task_history', 'comment_field')
    op.drop_column('task_history', 'location')
    op.drop_column('task_history', 'scheduled_at')
    op.drop_column('task_history', 'vehicle_info')
    op.drop_column('task_history', 'client')
    # ### end Alembic commands ###
