"""empty message

Revision ID: 5bd268c4363d
Revises: 707b6940527c
Create Date: 2025-10-31 18:38:19.142895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bd268c4363d'
down_revision: Union[str, Sequence[str], None] = '707b6940527c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_mappings_telegram_id'), table_name='telegram_mappings')
    op.drop_table('telegram_mappings')
    op.add_column('task_equipment', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('task_works', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('gos_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'gos_number')
    op.drop_column('task_works', 'quantity')
    op.drop_column('task_equipment', 'serial_number')
    op.create_table('telegram_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consumed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('linked_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], name=op.f('telegram_mappings_linked_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('telegram_mappings_pkey'))
    )
    op.create_index(op.f('ix_telegram_mappings_telegram_id'), 'telegram_mappings', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
