"""empty message

Revision ID: 5f1b16c3ebbc
Revises: 848e89bdd93e
Create Date: 2025-10-26 15:09:25.922197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1b16c3ebbc'
down_revision: Union[str, Sequence[str], None] = '848e89bdd93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('work_types', sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('work_types', sa.Column('montajnik_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('work_types', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('work_types', 'montajnik_price')
    op.drop_column('work_types', 'client_price')
    op.drop_table('contact_persons')
    op.drop_table('client_companies')
    # ### end Alembic commands ###
