"""empty message

Revision ID: 6688d1827d9a
Revises: c02989804305
Create Date: 2025-09-30 18:46:58.076004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6688d1827d9a'
down_revision: Union[str, Sequence[str], None] = 'c02989804305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('photos_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_logist', sa.Enum('waiting', 'approved', 'rejected', name='reportapproval'), nullable=False),
    sa.Column('approval_tech', sa.Enum('waiting', 'approved', 'rejected', name='reportapproval'), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reports_author_id'), 'task_reports', ['author_id'], unique=False)
    op.create_index(op.f('ix_task_reports_task_id'), 'task_reports', ['task_id'], unique=False)
    op.alter_column('broadcast_responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('broadcast_responses_task_id_fkey'), 'broadcast_responses', type_='foreignkey')
    op.drop_constraint(op.f('broadcast_responses_user_id_fkey'), 'broadcast_responses', type_='foreignkey')
    op.create_foreign_key(None, 'broadcast_responses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'broadcast_responses', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('equipment', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_task_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('task_attachments', sa.Column('telegram_file_id', sa.String(), nullable=True))
    op.add_column('task_attachments', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('task_attachments', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('task_attachments', sa.Column('size', sa.Integer(), nullable=True))
    op.drop_column('task_attachments', 'file_id')
    op.drop_constraint(op.f('task_equipment_task_id_fkey'), 'task_equipment', type_='foreignkey')
    op.drop_constraint(op.f('task_equipment_equipment_id_fkey'), 'task_equipment', type_='foreignkey')
    op.create_foreign_key(None, 'task_equipment', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_equipment', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('task_history_user_id_fkey'), 'task_history', type_='foreignkey')
    op.drop_constraint(op.f('task_history_task_id_fkey'), 'task_history', type_='foreignkey')
    op.create_foreign_key(None, 'task_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_history', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_works', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_works', 'work_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('task_works_work_type_id_fkey'), 'task_works', type_='foreignkey')
    op.drop_constraint(op.f('task_works_task_id_fkey'), 'task_works', type_='foreignkey')
    op.create_foreign_key(None, 'task_works', 'work_types', ['work_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_works', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'vehicle_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'returned_comment')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('returned_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'users', ['assigned_to'], ['id'])
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.alter_column('tasks', 'vehicle_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tasks', 'assigned_user_id')
    op.drop_constraint(None, 'task_works', type_='foreignkey')
    op.drop_constraint(None, 'task_works', type_='foreignkey')
    op.create_foreign_key(op.f('task_works_task_id_fkey'), 'task_works', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('task_works_work_type_id_fkey'), 'task_works', 'work_types', ['work_type_id'], ['id'])
    op.alter_column('task_works', 'work_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_works', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.create_foreign_key(op.f('task_history_task_id_fkey'), 'task_history', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('task_history_user_id_fkey'), 'task_history', 'users', ['user_id'], ['id'])
    op.alter_column('task_history', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'task_equipment', type_='foreignkey')
    op.drop_constraint(None, 'task_equipment', type_='foreignkey')
    op.create_foreign_key(op.f('task_equipment_equipment_id_fkey'), 'task_equipment', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(op.f('task_equipment_task_id_fkey'), 'task_equipment', 'tasks', ['task_id'], ['id'])
    op.add_column('task_attachments', sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task_attachments', 'size')
    op.drop_column('task_attachments', 'mime_type')
    op.drop_column('task_attachments', 'storage_key')
    op.drop_column('task_attachments', 'telegram_file_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_task_id_fkey'), 'notifications', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('equipment', 'price')
    op.drop_constraint(None, 'broadcast_responses', type_='foreignkey')
    op.drop_constraint(None, 'broadcast_responses', type_='foreignkey')
    op.create_foreign_key(op.f('broadcast_responses_user_id_fkey'), 'broadcast_responses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('broadcast_responses_task_id_fkey'), 'broadcast_responses', 'tasks', ['task_id'], ['id'])
    op.alter_column('broadcast_responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_task_reports_task_id'), table_name='task_reports')
    op.drop_index(op.f('ix_task_reports_author_id'), table_name='task_reports')
    op.drop_table('task_reports')
    # ### end Alembic commands ###
