"""empty message

Revision ID: 6b994ba6f37e
Revises: cd8c55128a9c
Create Date: 2026-01-26 19:30:57.471734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b994ba6f37e'
down_revision: Union[str, Sequence[str], None] = 'cd8c55128a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('client_companies', sa.Column('user_company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_client_companies_user_company_id'), 'client_companies', ['user_company_id'], unique=False)
    op.create_foreign_key(None, 'client_companies', 'user_companies', ['user_company_id'], ['id'], ondelete='CASCADE')
    op.add_column('equipment', sa.Column('user_company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_equipment_user_company_id'), 'equipment', ['user_company_id'], unique=False)
    op.create_foreign_key(None, 'equipment', 'user_companies', ['user_company_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('user_company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_user_company_id'), 'tasks', ['user_company_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'user_companies', ['user_company_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'user_companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('work_types', sa.Column('user_company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_work_types_user_company_id'), 'work_types', ['user_company_id'], unique=False)
    op.create_foreign_key(None, 'work_types', 'user_companies', ['user_company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_types', type_='foreignkey')
    op.drop_index(op.f('ix_work_types_user_company_id'), table_name='work_types')
    op.drop_column('work_types', 'user_company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_company_id'), table_name='tasks')
    op.drop_column('tasks', 'user_company_id')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_index(op.f('ix_equipment_user_company_id'), table_name='equipment')
    op.drop_column('equipment', 'user_company_id')
    op.drop_constraint(None, 'client_companies', type_='foreignkey')
    op.drop_index(op.f('ix_client_companies_user_company_id'), table_name='client_companies')
    op.drop_column('client_companies', 'user_company_id')
    op.drop_table('user_companies')
    # ### end Alembic commands ###
