"""empty message

Revision ID: 79633f114a15
Revises: 2273555f11be
Create Date: 2025-12-05 17:14:23.980420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79633f114a15'
down_revision: Union[str, Sequence[str], None] = '2273555f11be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('work_types', sa.Column('mont_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('work_types', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('work_types', 'mont_price')
    op.drop_column('work_types', 'client_price')
    # ### end Alembic commands ###
