"""empty message

Revision ID: 7ada9f1aa257
Revises: d0a2c23e8de0
Create Date: 2025-11-06 21:46:18.636875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ada9f1aa257'
down_revision: Union[str, Sequence[str], None] = 'd0a2c23e8de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('equipment_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('task_history', sa.Column('work_types_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'work_types_snapshot')
    op.drop_column('task_history', 'equipment_snapshot')
    # ### end Alembic commands ###
