"""empty message

Revision ID: 7c3908a05df0
Revises: d1a3a66fd99f
Create Date: 2025-10-26 15:26:42.951607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3908a05df0'
down_revision: Union[str, Sequence[str], None] = 'd1a3a66fd99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('contact_person_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_history_contact_person_id'), 'task_history', ['contact_person_id'], unique=False)
    op.create_foreign_key(None, 'task_history', 'contact_persons', ['contact_person_id'], ['id'], ondelete='SET NULL')
    op.drop_column('task_history', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_index(op.f('ix_task_history_contact_person_id'), table_name='task_history')
    op.drop_column('task_history', 'contact_person_id')
    # ### end Alembic commands ###
