"""empty message

Revision ID: 848e89bdd93e
Revises: 4c3e926e97fa
Create Date: 2025-10-22 14:29:40.775464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '848e89bdd93e'
down_revision: Union[str, Sequence[str], None] = '4c3e926e97fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'equipment_snapshot')
    op.drop_column('task_history', 'work_types_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('work_types_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('task_history', sa.Column('equipment_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
