# 90ec311184e8_*.py

"""Add detailed task history fields and event type

Revision ID: 90ec311184e8
Revises: 1627d125452f
Create Date: 2025-10-15 20:33:48.499579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90ec311184e8'
down_revision: Union[str, Sequence[str], None] = '1627d125452f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. ЯВНО СОЗДАЕМ ENUM ТИП ДО ЕГО ИСПОЛЬЗОВАНИЯ
    # Этот SQL создаст тип в PostgreSQL
    op.execute("CREATE TYPE taskhistoryeventtype AS ENUM ('FIELD_CHANGED', 'STATUS_CHANGED', 'REPORT_STATUS_CHANGED', 'REPORT_SUBMITTED', 'ATTACHMENT_ADDED', 'ATTACHMENT_REMOVED', 'ASSIGNED', 'UNASSIGNED')")

    # 2. Теперь можем добавлять столбец с этим типом
    op.add_column('task_history', sa.Column('event_type', sa.Enum('FIELD_CHANGED', 'STATUS_CHANGED', 'REPORT_STATUS_CHANGED', 'REPORT_SUBMITTED', 'ATTACHMENT_ADDED', 'ATTACHMENT_REMOVED', 'ASSIGNED', 'UNASSIGNED', name='taskhistoryeventtype'), nullable=True))
    op.add_column('task_history', sa.Column('field_name', sa.String(), nullable=True))
    op.add_column('task_history', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('task_history', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('task_history', sa.Column('related_entity_id', sa.Integer(), nullable=True))
    op.add_column('task_history', sa.Column('related_entity_type', sa.String(), nullable=True))
    
    # 3. Обновляем существующие столбцы
    op.alter_column('task_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.func.now())
    # action делаем nullable, как в модели
    op.alter_column('task_history', 'action',
               existing_type=postgresql.ENUM('new', 'accepted', 'started', 'completed', 'inspection', 'returned', name='taskstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Откатываем изменения столбцов
    op.alter_column('task_history', 'action',
               existing_type=postgresql.ENUM('new', 'accepted', 'started', 'completed', 'inspection', 'returned', name='taskstatus'),
               nullable=False) # Восстанавливаем, если было NOT NULL
    op.alter_column('task_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               server_default=None)

    # 2. Удаляем добавленные столбцы
    op.drop_column('task_history', 'related_entity_type')
    op.drop_column('task_history', 'related_entity_id')
    op.drop_column('task_history', 'new_value')
    op.drop_column('task_history', 'old_value')
    op.drop_column('task_history', 'field_name')
    op.drop_column('task_history', 'event_type')
    
    # 3. УДАЛЯЕМ СОЗДАННЫЙ ENUM ТИП
    # ВАЖНО: Это может не сработать, если на тип ещё ссылаются (например, если downgrade выполняется не сразу после upgrade)
    # В реальном проекте часто такие типы НЕ удаляют, чтобы не потерять данные.
    # op.execute("DROP TYPE taskhistoryeventtype")
    # ### end Alembic commands ###