"""empty message

Revision ID: 9141dd53763d
Revises: dd646dd1073e
Create Date: 2026-02-08 14:01:23.067035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9141dd53763d'
down_revision: Union[str, Sequence[str], None] = 'dd646dd1073e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('manager_status', sa.Enum('invoice_not_issued', 'invoice_issued', 'warranty', 'cash_payment', name='managerstatus'), nullable=True))
    op.create_index(op.f('ix_tasks_manager_status'), 'tasks', ['manager_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_manager_status'), table_name='tasks')
    op.drop_column('tasks', 'manager_status')
    # ### end Alembic commands ###
