"""empty message

Revision ID: 91b5c9c416bb
Revises: 7c3908a05df0
Create Date: 2025-10-26 15:35:47.288679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b5c9c416bb'
down_revision: Union[str, Sequence[str], None] = '7c3908a05df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('contact_person_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_contact_person_id'), 'tasks', ['contact_person_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'contact_persons', ['contact_person_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('client', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_contact_person_id'), table_name='tasks')
    op.drop_column('tasks', 'contact_person_id')
    # ### end Alembic commands ###
