"""empty message

Revision ID: 95b6b6ca6ea2
Revises: 155644727f45
Create Date: 2025-10-16 19:09:52.179953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b6b6ca6ea2'
down_revision: Union[str, Sequence[str], None] = '155644727f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('equipment_ids', sa.Text(), nullable=True))
    op.add_column('task_history', sa.Column('work_types_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'work_types_ids')
    op.drop_column('task_history', 'equipment_ids')
    # ### end Alembic commands ###
