"""empty message

Revision ID: 972c39853f86
Revises: 79633f114a15
Create Date: 2025-12-08 16:08:53.961594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972c39853f86'
down_revision: Union[str, Sequence[str], None] = '79633f114a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('equipment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_types', 'equipment')
    # ### end Alembic commands ###
