"""empty message

Revision ID: 9ba78ba595a3
Revises: 5bd268c4363d
Create Date: 2025-10-31 18:53:23.087031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba78ba595a3'
down_revision: Union[str, Sequence[str], None] = '5bd268c4363d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('gos_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'gos_number')
    # ### end Alembic commands ###
