"""empty message

Revision ID: a9cd18d687bb
Revises: 4756b4fc78e3
Create Date: 2025-10-06 20:30:07.261340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cd18d687bb'
down_revision: Union[str, Sequence[str], None] = '4756b4fc78e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_attachments', sa.Column('report_id', sa.Integer(), nullable=True))
    op.add_column('task_attachments', sa.Column('original_name', sa.String(), nullable=True))
    op.add_column('task_attachments', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.add_column('task_attachments', sa.Column('uploader_role', sa.String(), nullable=True))
    op.add_column('task_attachments', sa.Column('checksum', sa.String(length=128), nullable=True))
    op.add_column('task_attachments', sa.Column('processed', sa.Boolean(), nullable=False))
    op.add_column('task_attachments', sa.Column('error_text', sa.Text(), nullable=True))
    op.add_column('task_attachments', sa.Column('thumb_key', sa.String(), nullable=True))
    op.add_column('task_attachments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_attachments', 'storage_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task_attachments', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_task_attachments_report_id'), 'task_attachments', ['report_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_storage_key'), 'task_attachments', ['storage_key'], unique=False)
    op.create_index(op.f('ix_task_attachments_uploader_id'), 'task_attachments', ['uploader_id'], unique=False)
    op.drop_constraint(op.f('task_attachments_task_id_fkey'), 'task_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'task_attachments', 'task_reports', ['report_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_attachments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_attachments', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
    op.drop_column('task_attachments', 'telegram_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_attachments', sa.Column('telegram_file_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_attachments', type_='foreignkey')
    op.drop_constraint(None, 'task_attachments', type_='foreignkey')
    op.drop_constraint(None, 'task_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('task_attachments_task_id_fkey'), 'task_attachments', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_task_attachments_uploader_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_storage_key'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_report_id'), table_name='task_attachments')
    op.alter_column('task_attachments', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('task_attachments', 'storage_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('task_attachments', 'deleted_at')
    op.drop_column('task_attachments', 'thumb_key')
    op.drop_column('task_attachments', 'error_text')
    op.drop_column('task_attachments', 'processed')
    op.drop_column('task_attachments', 'checksum')
    op.drop_column('task_attachments', 'uploader_role')
    op.drop_column('task_attachments', 'uploader_id')
    op.drop_column('task_attachments', 'original_name')
    op.drop_column('task_attachments', 'report_id')
    # ### end Alembic commands ###
