"""empty message

Revision ID: c9e20c3285ce
Revises: 
Create Date: 2026-04-21 16:59:29.575513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9e20c3285ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_companies_user_company_id'), 'client_companies', ['user_company_id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_user_company_id'), 'districts', ['user_company_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_user_company_id'), 'equipment', ['user_company_id'], unique=False)
    op.create_table('work_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mont_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('logist_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tech_supp_require', sa.Boolean(), nullable=True),
    sa.Column('user_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_types_user_company_id'), 'work_types', ['user_company_id'], unique=False)
    op.create_table('contact_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'logist', 'montajnik', 'tech_supp', 'manager', 'super_admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['user_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('contact_person_id', sa.Integer(), nullable=True),
    sa.Column('contact_person_phone', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_info', sa.String(), nullable=True),
    sa.Column('gos_number', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'accepted', 'on_the_road', 'started', 'on_site', 'completed', 'inspection', 'returned', 'archived', 'assigned', name='taskstatus'), nullable=True),
    sa.Column('manager_status', sa.Enum('invoice_not_issued', 'invoice_issued', 'warranty', 'cash_payment', name='managerstatus'), nullable=True),
    sa.Column('assignment_type', sa.Enum('individual', 'broadcast', name='assignmenttype'), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('logist_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('logist_reward', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('montajnik_reward', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_company_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('logist_performance', sa.Enum('good', 'bad', name='logistperformance'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('photo_required', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_person_id'], ['contact_persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_assignment_type'), 'tasks', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_tasks_company_id'), 'tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_tasks_contact_person_id'), 'tasks', ['contact_person_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_district_id'), 'tasks', ['district_id'], unique=False)
    op.create_index(op.f('ix_tasks_is_draft'), 'tasks', ['is_draft'], unique=False)
    op.create_index(op.f('ix_tasks_logist_performance'), 'tasks', ['logist_performance'], unique=False)
    op.create_index(op.f('ix_tasks_manager_status'), 'tasks', ['manager_status'], unique=False)
    op.create_index(op.f('ix_tasks_scheduled_at'), 'tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_company_id'), 'tasks', ['user_company_id'], unique=False)
    op.create_table('broadcast_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_first', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_responses_task_id'), 'broadcast_responses', ['task_id'], unique=False)
    op.create_index(op.f('ix_broadcast_responses_user_id'), 'broadcast_responses', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('task_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_equipment_equipment_id'), 'task_equipment', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_task_equipment_task_id'), 'task_equipment', ['task_id'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('new', 'accepted', 'on_the_road', 'started', 'on_site', 'completed', 'inspection', 'returned', 'archived', 'assigned', name='taskstatus'), nullable=True),
    sa.Column('event_type', sa.Enum('field_changed', 'status_changed', 'report_status_changed', 'report_submitted', 'attachment_added', 'attachment_removed', 'assigned', 'unassigned', 'created', 'published', 'updated', name='taskhistoryeventtype'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('contact_person_id', sa.Integer(), nullable=True),
    sa.Column('contact_person_phone', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_info', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('comment_field', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'accepted', 'on_the_road', 'started', 'on_site', 'completed', 'inspection', 'returned', 'archived', 'assigned', name='taskstatus'), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('client_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('montajnik_reward', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('photo_required', sa.Boolean(), nullable=True),
    sa.Column('assignment_type', sa.Enum('individual', 'broadcast', name='assignmenttype'), nullable=True),
    sa.Column('gos_number', sa.String(), nullable=True),
    sa.Column('equipment_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_types_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_person_id'], ['contact_persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_history_assigned_user_id'), 'task_history', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_task_history_company_id'), 'task_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_task_history_contact_person_id'), 'task_history', ['contact_person_id'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_history_user_id'), 'task_history', ['user_id'], unique=False)
    op.create_table('task_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('photos_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_logist', sa.Enum('waiting', 'approved', 'rejected', name='reportapproval'), nullable=False),
    sa.Column('approval_tech', sa.Enum('waiting', 'approved', 'rejected', name='reportapproval'), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at_logist', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at_tech_supp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reports_author_id'), 'task_reports', ['author_id'], unique=False)
    op.create_index(op.f('ix_task_reports_task_id'), 'task_reports', ['task_id'], unique=False)
    op.create_table('task_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_by_montajnik', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_works_task_id'), 'task_works', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_works_work_type_id'), 'task_works', ['work_type_id'], unique=False)
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('photo', 'document', 'video', name='filetype'), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('uploader_role', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('thumb_key', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['task_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attachments_report_id'), 'task_attachments', ['report_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_storage_key'), 'task_attachments', ['storage_key'], unique=False)
    op.create_index(op.f('ix_task_attachments_task_id'), 'task_attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_uploader_id'), 'task_attachments', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_attachments_uploader_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_task_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_storage_key'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_report_id'), table_name='task_attachments')
    op.drop_table('task_attachments')
    op.drop_index(op.f('ix_task_works_work_type_id'), table_name='task_works')
    op.drop_index(op.f('ix_task_works_task_id'), table_name='task_works')
    op.drop_table('task_works')
    op.drop_index(op.f('ix_task_reports_task_id'), table_name='task_reports')
    op.drop_index(op.f('ix_task_reports_author_id'), table_name='task_reports')
    op.drop_table('task_reports')
    op.drop_index(op.f('ix_task_history_user_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_contact_person_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_company_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_assigned_user_id'), table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_task_equipment_task_id'), table_name='task_equipment')
    op.drop_index(op.f('ix_task_equipment_equipment_id'), table_name='task_equipment')
    op.drop_table('task_equipment')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_broadcast_responses_user_id'), table_name='broadcast_responses')
    op.drop_index(op.f('ix_broadcast_responses_task_id'), table_name='broadcast_responses')
    op.drop_table('broadcast_responses')
    op.drop_index(op.f('ix_tasks_user_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduled_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_manager_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_logist_performance'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_draft'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_district_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_contact_person_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignment_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('contact_persons')
    op.drop_index(op.f('ix_work_types_user_company_id'), table_name='work_types')
    op.drop_table('work_types')
    op.drop_index(op.f('ix_equipment_user_company_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_districts_user_company_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_client_companies_user_company_id'), table_name='client_companies')
    op.drop_table('client_companies')
    op.drop_table('user_companies')
    # ### end Alembic commands ###
