"""empty message

Revision ID: d0a2c23e8de0
Revises: 28dcc5470257
Create Date: 2025-11-06 20:54:46.989040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a2c23e8de0'
down_revision: Union[str, Sequence[str], None] = '28dcc5470257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('work_types', 'client_price')
    op.drop_column('work_types', 'montajnik_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('montajnik_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('work_types', sa.Column('client_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('work_types', 'price')
    # ### end Alembic commands ###
