"""empty message

Revision ID: e222e9dfa89c
Revises: 9141dd53763d
Create Date: 2026-02-12 13:06:19.650876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e222e9dfa89c'
down_revision: Union[str, Sequence[str], None] = '9141dd53763d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('logist_performance', sa.Enum('good', 'bad', name='logistperformance'), nullable=True))
    op.create_index(op.f('ix_tasks_logist_performance'), 'tasks', ['logist_performance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_logist_performance'), table_name='tasks')
    op.drop_column('tasks', 'logist_performance')
    # ### end Alembic commands ###
