"""empty message

Revision ID: f647add9747e
Revises: dc416aeac142
Create Date: 2025-11-10 21:10:53.861856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f647add9747e'
down_revision: Union[str, Sequence[str], None] = 'dc416aeac142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_types', sa.Column('tech_supp_require', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_types', 'tech_supp_require')
    # ### end Alembic commands ###
